#!/usr/bin/env bash
# I am using zsh instead of bash.  I was having some troubles using bash with
# arrays.  Didn't want to investigate, so I just did zsh
pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "Unstowing $folder"
    python -m dploy unstow $folder $HOME
done
popd
