-- Set lualine as statusline
-- See `:help lualine.txt`
-- require('lualine').setup {
--   options = {
--     icons_enabled = false,
--     theme = 'gruvbox',
--     component_separators = '|',
--     section_separators = '',
--   },
-- }
