#!/usr/bin/env bash

alias xsc="xclip -selection clipboard"
alias esc="$HOME/.config/sway/config"

alias vim="$VIM"
alias vims="NVIM_LISTEN_ADDRESS=/tmp/nvim $VIM"
alias work="cd ~/work"

alias cbp="cat $DOTFILES/bash/.bash_profile"
alias ebp="$VIM $DOTFILES/bash/.bash_profile"
alias etc="$VIM $DOTFILES/tmux/.tmux.conf"
alias bp="dotFileInstall && source ~/.bashrc"
alias enrc="pushd $DOTFILES/nvim/.config/nvim && $VIM $DOTFILES/nvim/.config/nvim/init.vim && popd"
alias eirc="$VIM $XDG_CONFIG_HOME/i3/i3config"
alias cvrc="cat $DOTFILES/vimrc/.vimrc"
alias dotFileInstall="$DOTFILES/install"

alias pjson="python -mjson.tool"
alias killBT="rfkill block bluetooth"
alias unKillBT="rfkill unblock bluetooth"
alias cclip="xclip -selection clipboard"
alias pclip="xclip -selection clipboard"

alias cnpm="cat ~/.npmrc"
alias pnpm='rm ~/.npmrc'

alias showPath="sed 's/:/\n/g' <<< '$PATH'"

# ls
alias la="ls -la"
alias ls="ls -F --color=auto --show-control-chars"

# mock cli ¯\_(ツ)_/¯ works
alias identity="$HOME/work/mycli/identity/myidentity"
alias qp="$HOME/work/mycli/quickerpay/myquickerpay"

# environment aliases
alias le="listEnv"

# lazy git
alias lg="lazygit"

# terraform
alias tf="terraform"

# screenkey
alias sk=$SCRIPTS/screenkey.sh
alias killSK=$SCRIPTS/kill_screenkey.sh

