#!/usr/bin/env bash

alias xsc="xclip -selection clipboard"
alias esc="$HOME/.config/sway/config"

alias vim="$VIM"
alias vims="NVIM_LISTEN_ADDRESS=/tmp/nvim $VIM"
alias work="cd ~/work"

alias cbp="cat $DOTFILES/bash/.bash_profile"
alias ebp="$VIM $DOTFILES/bash/.bash_profile"
alias etc="$VIM $DOTFILES/tmux/.tmux.conf"
alias bp="dotFileInstall && source ~/.bashrc"
alias enrc="pushd $DOTFILES/nvim/.config/nvim && $VIM $DOTFILES/nvim/.config/nvim/init.lua && popd"
alias eirc="$VIM $XDG_CONFIG_HOME/i3/i3config"
alias cvrc="cat $DOTFILES/vimrc/.vimrc"
alias dotFileInstall="$DOTFILES/install"

function edit-dir() {
    pushd $1 && $VIM $1 && popd
}

alias enp="edit-dir $DOTFILES/../AppData/Local/nvim-data/site/pack/packer/start"

alias pjson="python -mjson.tool"
alias killBT="rfkill block bluetooth"
alias unKillBT="rfkill unblock bluetooth"
alias cclip="xclip -selection clipboard"
alias pclip="xclip -selection clipboard"

alias cnpm="cat ~/.npmrc"
alias pnpm='rm ~/.npmrc'

alias showPath="sed 's/:/\n/g' <<< '$PATH'"

# mock cli ¯\_(ツ)_/¯ works
alias identity="$HOME/work/mycli/identity/myidentity"
alias qp="$HOME/work/mycli/quickerpay/myquickerpay"
alias k1="$HOME/work/mycli/k1/k1"

# environment aliases
alias le="listEnv"

# lazy git
alias lg="lazygit"

# screenkey
alias sk=$SCRIPTS/screenkey.sh
alias killSK=$SCRIPTS/kill_screenkey.sh

