#!/usr/bin/env bash
#addToPathFront $DENO_INSTALL
#addToPath /home/aenichols/personal/lua-language-server/bin/Linux
#addToPath /usr/local/go/bin
#addToPath $GOPATH/bin
##addToPath $HOME/work/wrapper
##addToPath /usr/local/netflix/tvui-automation-analyzer
##addToPath /usr/local/netflix/encoders/bin/
#addToPath $HOME/.yarn/bin
#addToPath /usr/lib/llvm-8/bin
##addToPath $HOME/personal/uhh/build
#addToPath $HOME/.cargo/bin
#addToPath $HOME/.rustup
#
## ccache
#addToPathFront /usr/lib/ccache

addToPathFront "/C/Program Files (x86)/Microsoft Visual Studio/2019/Professional/MSBuild/Current/Bin"
#addToPathFront "/C/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/MSBuild/Current/Bin"
addToPathFront "/C/Program Files/Microsoft Visual Studio/2022/Professional/MSBuild/Current/Bin"

# OmniSharp.exe -v (find MSBuild Instance - Registered MSBuild Instances))
# {"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.MSBuild.Discovery.MSBuildLocator","Message":"Located
# 3 MSBuild instance(s)\r\n
#
# 1: Visual Studio Professional 2019 16.11.32106.194 16.11.2 - \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\MSBuild\\Current\\Bin\"\r\n
# 2: Visual Studio Build Tools 2022 17.0.32112.339 17.0.0 - \"C:\\Program Files (x86)\\Micro soft Visual Studio\\2022\\BuildTools\\MSBuild\\Current\\Bin\"\r\n
# 3: StandAlone 17.0.0 - \"C:\\OmniSharp\\.msbuild\\Current\\Bin\""},"Seq":14,"Type":"event"}
#
#
# {"Event":"log","Body":{"LogLevel":"DEBUG","Name":"OmniSharp.CompositionHostBuilder","Message":"MSBuild
#     instance Visual Studio Professional 2019 16.11.32106.194 16.11.2 scored
#     at 2"},"Seq":15,"Type":"event"}
