# generated by Git for Windows
# test -f ~/.profile && . ~/.profile
# test -f ~/.bashrc && . ~/.bashrc
#
# for setting environment variables and sourcing files

export XDG_CONFIG_HOME=$HOME/.config
VIM="nvim"

# my environment variables
export SCRIPTS=$HOME/.local/scripts
export ID="$HOME/work/Identity/src/Identity.Server"
export AU="$HOME/work/ConnectBooster/ConnectBooster.Frontend"
export QP="$HOME/work/QuickerPay/Source"
export CLI="$HOME/work/mycli"
export KOB="$HOME/work/k1/backend/src"
export KOF="$HOME/work/k1/frontend/KaseyaOne"
export KOD="$HOME/work/k1/backend/docker"

PERSONAL=$XDG_CONFIG_HOME/personal
source $PERSONAL/env
for i in `/usr/bin/find -L $PERSONAL -type f | grep ".*personal/.*"`; do
    source $i
done

source $HOME/.secrets
