-- local function get_my_project_root(root_dir)
--     local project_root = root_dir .. '/node_modules'
--     return project_root
-- end
--
-- local ts_probe_dir_raw = "~/scoop/persist/nvm/nodejs/v18.20.8/node_modules/typescript/lib"
-- local ts_probe_dir = vim.fn.expand(ts_probe_dir_raw)
--
-- local ng_probe_dir_raw = "~/scoop/persist/nvm/nodejs/v18.20.8/node_modules/@angular/language-server/bin"
-- local ng_probe_dir = vim.fn.expand(ng_probe_dir_raw)
--
-- local root_dir = vim.fn.getcwd()
-- local project_root = get_my_project_root(root_dir)
--
-- local cmd = {
--     'ngserver',
--     '--stdio',
--     '--tsProbeLocations',
--     ts_probe_dir,
--     '--ngProbeLocations',
--     ng_probe_dir,
--     '--angularCoreVersion',
--     '15.2.6',
--     '--logFile', '/tmp/angularls.log',
--     '--logVerbosity',
--     'verbose',
-- }
--
-- local filetypes = { 'typescript', 'html', 'typescriptreact', 'typescript.tsx', 'htmlangular' }
--
-- return {
--     cmd = cmd,
--     hint = { enable = true },
--     root_markers = { 'angular.json' },
--     filetypes = filetypes,
-- }
